package com.shortener.linkshorten;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;

@DynamoDBTable(tableName = "links")
public class LinkEntity {
    private String id;

    private String shortLink;
    private String longLink;

    private int uniqueIncrementer;

    public LinkEntity(String shortLink, String longLink) {
        this.shortLink = shortLink;
        this.longLink = longLink;
    }

    public LinkEntity(String longLink, int uniqueIncrementer) {
        this.longLink = longLink;
        this.uniqueIncrementer = uniqueIncrementer;
    }

    public LinkEntity() {
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @JsonIgnore
    public String getId() {
        return id;
    }

    public String getShortLink() {
        return shortLink;
    }

    public String getLongLink() {
        return longLink;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setShortLink(String shortLink) {
        this.shortLink = shortLink;
    }

    public void setLongLink(String longLink) {
        this.longLink = longLink;
    }

    @JsonIgnore
    public int getUniqueIncrementer() {
        return uniqueIncrementer;
    }

    public void setUniqueIncrementer(int uniqueIncrementer) {
        this.uniqueIncrementer = uniqueIncrementer;
    }
}
